spring.application.name=api-gateway
server.port=8080

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#Rutas hacia ms-auth
spring.cloud.gateway.server.webflux.routes[0].id=ms-auth-login
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ms-auth
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=ms-auth-users
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ms-auth
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webflux.routes[2].id=ms-auth-roles
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ms-auth
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/roles/**

spring.cloud.gateway.server.webflux.routes[3].id=ms-auth-permissions
spring.cloud.gateway.server.webflux.routes[3].uri=lb://ms-auth
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/permissions/**

#Rutas hacia ms-product
spring.cloud.gateway.server.webflux.routes[4].id=ms-product
spring.cloud.gateway.server.webflux.routes[4].uri=lb://ms-product
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/products/**

#JWT
jwt.secret=clave-super-secreta-tfi-2024-debe-tener-256-bits-minimo